### ISSUE TITLE
error during minifying with YUI compressor

### ISSUE THREAD

**Issue by chris-ti8m** [flowplayer/flowplayer-hlsjs#68]
# Error during minifying with YUI compressor
flowplayer-hlsjs.js cannot be minified with the YUI compressor. The flowplayer-hlsjs.js is the latest version 1.0.7. Stacktrace of the compressor is attached at the bottom.

## Howto reproduce
This can be verified with the [online compressor](http://refresh-sf.com/). Copy and paste the sources from flowplayer-hlsjs.js into the code-field of the compressor. In the YUI Compressor tab select the option "Use YUI Compressor instead of UglifyJS/Clean-CSS.". Use the Javascript button to start the Javascript minifaction process of the input. The compressor will show the stacktrace below. 

## Stacktrace

[ERROR] in -
  783:54:missing name after . operator
[ERROR] in -
  784:48:syntax error
[ERROR] in -
  788:38:syntax error
[ERROR] in -
  793:32:missing ; before statement
[ERROR] in -
  794:38:syntax error
[ERROR] in -
  797:31:missing ; before statement
[ERROR] in -
  798:38:syntax error
[ERROR] in -
  801:30:missing ; before statement
[ERROR] in -
  802:38:syntax error
[ERROR] in -
  805:32:missing ) after argument list
[ERROR] in -
  806:43:missing ; before statement
[ERROR] in -
  807:42:syntax error
[ERROR] in -
  808:29:syntax error
[ERROR] in -
  809:26:syntax error
[ERROR] in -
  811:31:syntax error
[ERROR] in -
  812:38:syntax error
[ERROR] in -
  814:25:syntax error
[ERROR] in -
  816:32:syntax error
[ERROR] in -
  817:38:missing ; before statement
[ERROR] in -
  828:29:syntax error
[ERROR] in -
  830:21:syntax error
[ERROR] in -
  844:23:invalid return
[ERROR] in -
  845:13:syntax error
[ERROR] in -
  880:5:syntax error
[ERROR] in -
  886:1:syntax error
[ERROR] in -
  1:0:Compilation produced 25 syntax errors.
org.mozilla.javascript.EvaluatorException: Compilation produced 25 syntax errors.
	at com.yahoo.platform.yui.compressor.YUICompressor$1.runtimeError(YUICompressor.java:172)
	at org.mozilla.javascript.Parser.parse(Parser.java:396)
	at org.mozilla.javascript.Parser.parse(Parser.java:340)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
	at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
	at com.yahoo.platform.yui.compressor.YUICompressor.main(YUICompressor.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.yahoo.platform.yui.compressor.Bootstrap.main(Bootstrap.java:21)

**Comment by blacktrash** [comment]
As per https://github.com/flowplayer/flowplayer-hlsjs#building-the-plugin building is nodejs based, and uglifyjs is used for minification (as for all other plugins): https://github.com/flowplayer/flowplayer-hlsjs/blob/master/package.json#L11
